import { PokemonLevel } from "../utils/pokemon-level.interface";

export const LEVELS: PokemonLevel[] = [
  {
    name: "React",
    type: "FRAMEWORK",
    id: 1,
  },

  { type: "POKEMON", id: 300, name: "Pikachu" },
  { type: "POKEMON", id: 301, name: "Charizard" },
  { type: "POKEMON", id: 302, name: "Bulbasaur" },
  { type: "POKEMON", id: 303, name: "Squirtle" },
  { type: "POKEMON", id: 304, name: "Gengar" },
  { type: "POKEMON", id: 305, name: "Eevee" },
  { type: "POKEMON", id: 306, name: "Snorlax" },
  { type: "POKEMON", id: 307, name: "Jigglypuff" },
  { type: "POKEMON", id: 308, name: "Meowth" },
  { type: "POKEMON", id: 309, name: "Psyduck" },
  { type: "POKEMON", id: 310, name: "Machamp" },
  { type: "POKEMON", id: 311, name: "Lucario" },
  { type: "POKEMON", id: 312, name: "Zubat" },
  { type: "POKEMON", id: 313, name: "Rattata" },
  { type: "POKEMON", id: 314, name: "Caterpie" },
  { type: "POKEMON", id: 315, name: "Abra" },
  { type: "POKEMON", id: 316, name: "Gyarados" },
  { type: "POKEMON", id: 317, name: "Dragonite" },
  { type: "POKEMON", id: 318, name: "Mewtwo" },
  { type: "POKEMON", id: 319, name: "Articuno" },
  { type: "POKEMON", id: 320, name: "Zapdos" },
  { type: "POKEMON", id: 321, name: "Moltres" },
  { type: "POKEMON", id: 322, name: "Sandshrew" },
  { type: "POKEMON", id: 323, name: "Diglett" },
  { type: "POKEMON", id: 324, name: "Poliwag" },
  { type: "POKEMON", id: 325, name: "Magnemite" },
  { type: "POKEMON", id: 326, name: "Grimer" },
  { type: "POKEMON", id: 327, name: "Gastly" },
  { type: "POKEMON", id: 328, name: "Onix" },
  { type: "POKEMON", id: 329, name: "Voltorb" },
  { type: "POKEMON", id: 330, name: "Ditto" },
  { type: "POKEMON", id: 331, name: "Kabuto" },
  { type: "POKEMON", id: 332, name: "Aerodactyl" },
  { type: "POKEMON", id: 333, name: "Dratini" },
  { type: "POKEMON", id: 334, name: "Chikorita" },
  { type: "POKEMON", id: 335, name: "Cyndaquil" },
  { type: "POKEMON", id: 336, name: "Totodile" },
  { type: "POKEMON", id: 337, name: "Hoothoot" },
  { type: "POKEMON", id: 338, name: "Ledyba" },
  { type: "POKEMON", id: 339, name: "Togepi" },
  { type: "POKEMON", id: 340, name: "Mareep" },
  { type: "POKEMON", id: 341, name: "Sudowoodo" },
  { type: "POKEMON", id: 342, name: "Hoppip" },
  { type: "POKEMON", id: 343, name: "Sunkern" },
  { type: "POKEMON", id: 344, name: "Wooper" },
  { type: "POKEMON", id: 345, name: "Espeon" },
  { type: "POKEMON", id: 346, name: "Umbreon" },
  { type: "POKEMON", id: 347, name: "Murkrow" },
  { type: "POKEMON", id: 348, name: "Slowking" },
  { type: "POKEMON", id: 349, name: "Steelix" },
  { type: "POKEMON", id: 350, name: "Scizor" },
  { type: "POKEMON", id: 351, name: "Shuckle" },
  { type: "POKEMON", id: 352, name: "Sneasel" },
  { type: "POKEMON", id: 353, name: "Teddiursa" },
  { type: "POKEMON", id: 354, name: "Slugma" },
  { type: "POKEMON", id: 355, name: "Swinub" },
  { type: "POKEMON", id: 356, name: "Porygon2" },
  { type: "POKEMON", id: 357, name: "Smeargle" },
  { type: "POKEMON", id: 358, name: "Tyrogue" },
  { type: "POKEMON", id: 359, name: "Hitmontop" },
  { type: "POKEMON", id: 360, name: "Elekid" },
  { type: "POKEMON", id: 361, name: "Magby" },
  { type: "POKEMON", id: 362, name: "Miltank" },
  { type: "POKEMON", id: 363, name: "Blissey" },
  { type: "POKEMON", id: 364, name: "Raikou" },
  { type: "POKEMON", id: 365, name: "Entei" },
  { type: "POKEMON", id: 366, name: "Suicune" },
  { type: "POKEMON", id: 367, name: "Larvitar" },
  { type: "POKEMON", id: 368, name: "Pupitar" },
  { type: "POKEMON", id: 369, name: "Tyranitar" },
  { type: "POKEMON", id: 370, name: "Treecko" },
  { type: "POKEMON", id: 371, name: "Torchic" },
  { type: "POKEMON", id: 372, name: "Mudkip" },
  { type: "POKEMON", id: 373, name: "Poochyena" },
  { type: "POKEMON", id: 374, name: "Zigzagoon" },
  { type: "POKEMON", id: 375, name: "Lotad" },
  { type: "POKEMON", id: 376, name: "Seedot" },
  { type: "POKEMON", id: 377, name: "Ralts" },
  { type: "POKEMON", id: 378, name: "Slakoth" },
  { type: "POKEMON", id: 379, name: "Makuhita" },
  { type: "POKEMON", id: 380, name: "Nosepass" },
  { type: "POKEMON", id: 381, name: "Skitty" },
  { type: "POKEMON", id: 382, name: "Sableye" },
  { type: "POKEMON", id: 383, name: "Mawile" },
  { type: "POKEMON", id: 384, name: "Aron" },
  { type: "POKEMON", id: 385, name: "Meditite" },
  { type: "POKEMON", id: 386, name: "Electrike" },
  { type: "POKEMON", id: 387, name: "Plusle" },
  { type: "POKEMON", id: 388, name: "Minun" },
  { type: "POKEMON", id: 389, name: "Volbeat" },
  { type: "POKEMON", id: 390, name: "Illumise" },
  { type: "POKEMON", id: 391, name: "Roselia" },
  { type: "POKEMON", id: 392, name: "Gulpin" },
  { type: "POKEMON", id: 393, name: "Carvanha" },
  { type: "POKEMON", id: 394, name: "Wailmer" },
  { type: "POKEMON", id: 395, name: "Numel" },
  { type: "POKEMON", id: 396, name: "Torkoal" },
  { type: "POKEMON", id: 397, name: "Spoink" },
  { type: "POKEMON", id: 398, name: "Trapinch" },
  { type: "POKEMON", id: 399, name: "Cacnea" },
  { type: "POKEMON", id: 400, name: "Swablu" },
  { type: "POKEMON", id: 401, name: "Zangoose" },
  { type: "POKEMON", id: 402, name: "Seviper" },
  { type: "POKEMON", id: 403, name: "Lunatone" },
  { type: "POKEMON", id: 404, name: "Solrock" },
  { type: "POKEMON", id: 405, name: "Barboach" },
  { type: "POKEMON", id: 406, name: "Corphish" },
  { type: "POKEMON", id: 407, name: "Baltoy" },
  { type: "POKEMON", id: 408, name: "Lileep" },
  { type: "POKEMON", id: 409, name: "Anorith" },
  { type: "POKEMON", id: 410, name: "Feebas" },
  { type: "POKEMON", id: 411, name: "Spheal" },
  { type: "POKEMON", id: 412, name: "Bagon" },
  { type: "POKEMON", id: 413, name: "Beldum" },
  { type: "POKEMON", id: 414, name: "Regirock" },
  { type: "POKEMON", id: 415, name: "Regice" },
  { type: "POKEMON", id: 416, name: "Registeel" },
  { type: "POKEMON", id: 417, name: "Latias" },
  { type: "POKEMON", id: 418, name: "Latios" },
  { type: "POKEMON", id: 419, name: "Kyogre" },
  { type: "POKEMON", id: 420, name: "Groudon" },
  { type: "POKEMON", id: 421, name: "Rayquaza" },
  { type: "POKEMON", id: 422, name: "Jirachi" },
  { type: "POKEMON", id: 423, name: "Deoxys" },
  { type: "POKEMON", id: 424, name: "Turtwig" },
  { type: "POKEMON", id: 425, name: "Chimchar" },
  { type: "POKEMON", id: 426, name: "Piplup" },
  { type: "POKEMON", id: 427, name: "Starly" },
  { type: "POKEMON", id: 428, name: "Bidoof" },
  { type: "POKEMON", id: 429, name: "Shinx" },
  { type: "POKEMON", id: 430, name: "Budew" },
  { type: "POKEMON", id: 431, name: "Cranidos" },
  { type: "POKEMON", id: 432, name: "Shieldon" },
  { type: "POKEMON", id: 433, name: "Burmy" },
  { type: "POKEMON", id: 434, name: "Combee" },
  { type: "POKEMON", id: 435, name: "Pachirisu" },
  { type: "POKEMON", id: 436, name: "Buizel" },
  { type: "POKEMON", id: 437, name: "Cherubi" },
  { type: "POKEMON", id: 438, name: "Shellos" },
  { type: "POKEMON", id: 439, name: "Drifloon" },
  { type: "POKEMON", id: 440, name: "Buneary" },
  { type: "POKEMON", id: 441, name: "Glameow" },
  { type: "POKEMON", id: 442, name: "Chingling" },
  { type: "POKEMON", id: 443, name: "Stunky" },
  { type: "POKEMON", id: 444, name: "Bronzor" },
  { type: "POKEMON", id: 445, name: "Bonsly" },
  { type: "POKEMON", id: 446, name: "Mime Jr." },
  { type: "POKEMON", id: 447, name: "Happiny" },
  { type: "POKEMON", id: 448, name: "Chatot" },
  { type: "POKEMON", id: 449, name: "Spiritomb" },
  { type: "POKEMON", id: 450, name: "Gible" },
  { type: "POKEMON", id: 451, name: "Munchlax" },
  { type: "POKEMON", id: 452, name: "Riolu" },
  { type: "POKEMON", id: 453, name: "Hippopotas" },
  { type: "POKEMON", id: 454, name: "Skorupi" },
  { type: "POKEMON", id: 455, name: "Croagunk" },
  { type: "POKEMON", id: 456, name: "Carnivine" },
  { type: "POKEMON", id: 457, name: "Finneon" },
  { type: "POKEMON", id: 458, name: "Mantyke" },
  { type: "POKEMON", id: 459, name: "Snover" },
  { type: "POKEMON", id: 460, name: "Rotom" },
  { type: "POKEMON", id: 461, name: "Uxie" },
  { type: "POKEMON", id: 462, name: "Mesprit" },
  { type: "POKEMON", id: 463, name: "Azelf" },
  { type: "POKEMON", id: 464, name: "Dialga" },
  { type: "POKEMON", id: 465, name: "Palkia" },
  { type: "POKEMON", id: 466, name: "Heatran" },
  { type: "POKEMON", id: 467, name: "Regigigas" },
  { type: "POKEMON", id: 468, name: "Giratina" },
  { type: "POKEMON", id: 469, name: "Cresselia" },
  { type: "POKEMON", id: 470, name: "Phione" },
  { type: "POKEMON", id: 471, name: "Manaphy" },
  { type: "POKEMON", id: 472, name: "Darkrai" },
  { type: "POKEMON", id: 473, name: "Shaymin" },
  { type: "POKEMON", id: 474, name: "Arceus" },
  {
    name: "Angular",
    type: "FRAMEWORK",
    id: 2,
  },
  {
    name: "Vue",
    type: "FRAMEWORK",
    id: 3,
  },
  {
    name: "Next",
    type: "FRAMEWORK",
    id: 4,
  },
  {
    name: "Nuxt",
    type: "FRAMEWORK",
    id: 5,
  },
  {
    name: "Svelte",
    type: "FRAMEWORK",
    id: 6,
  },
  {
    name: "Express",
    type: "FRAMEWORK",
    id: 7,
  },
  {
    name: "NestJS",
    type: "FRAMEWORK",
    id: 8,
  },
  {
    name: "Meteor",
    type: "FRAMEWORK",
    id: 9,
  },
  {
    name: "Ember",
    type: "FRAMEWORK",
    id: 10,
  },
  {
    name: "Django",
    type: "FRAMEWORK",
    id: 11,
  },
  {
    name: "Flask",
    type: "FRAMEWORK",
    id: 12,
  },
  {
    name: "FastAPI",
    type: "FRAMEWORK",
    id: 13,
  },
  {
    name: "Pyramid",
    type: "FRAMEWORK",
    id: 14,
  },
  {
    name: "Bottle",
    type: "FRAMEWORK",
    id: 15,
  },
  {
    name: "Tornado",
    type: "FRAMEWORK",
    id: 16,
  },
  {
    name: "Falcon",
    type: "FRAMEWORK",
    id: 17,
  },
  {
    name: "Web2py",
    type: "FRAMEWORK",
    id: 18,
  },
  {
    name: "Ruby on Rails",
    type: "FRAMEWORK",
    id: 19,
  },
  {
    name: "Sinatra",
    type: "FRAMEWORK",
    id: 20,
  },
  {
    name: "Hanami",
    type: "FRAMEWORK",
    id: 21,
  },
  {
    name: "Spring Boot",
    type: "FRAMEWORK",
    id: 22,
  },
  {
    name: "Struts",
    type: "FRAMEWORK",
    id: 23,
  },
  {
    name: "Vaadin",
    type: "FRAMEWORK",
    id: 24,
  },
  {
    name: "Play ",
    type: "FRAMEWORK",
    id: 25,
  },
  {
    name: "Micronaut",
    type: "FRAMEWORK",
    id: 26,
  },
  {
    name: "Laravel",
    type: "FRAMEWORK",
    id: 27,
  },
  {
    name: "Symfony",
    type: "FRAMEWORK",
    id: 28,
  },
  {
    name: "CodeIgniter",
    type: "FRAMEWORK",
    id: 29,
  },
  {
    name: "CakePHP",
    type: "FRAMEWORK",
    id: 30,
  },
  {
    name: "Yii",
    type: "FRAMEWORK",
    id: 31,
  },
  {
    name: "Slim ",
    type: "FRAMEWORK",
    id: 32,
  },
  {
    name: "ASP.NET Core",
    type: "FRAMEWORK",
    id: 33,
  },
  {
    name: "Blazor",
    type: "FRAMEWORK",
    id: 34,
  },
  {
    name: "NancyFx",
    type: "FRAMEWORK",
    id: 35,
  },
  {
    name: "Gin",
    type: "FRAMEWORK",
    id: 36,
  },
  {
    name: "Echo",
    type: "FRAMEWORK",
    id: 37,
  },
  {
    name: "Revel",
    type: "FRAMEWORK",
    id: 38,
  },
  {
    name: "Fiber",
    type: "FRAMEWORK",
    id: 39,
  },
  {
    name: "Beego",
    type: "FRAMEWORK",
    id: 40,
  },
  {
    name: "Rocket",
    type: "FRAMEWORK",
    id: 41,
  },
  {
    name: "Actix Web",
    type: "FRAMEWORK",
    id: 42,
  },
  {
    name: "Warp",
    type: "FRAMEWORK",
    id: 43,
  },
  {
    name: "Axum",
    type: "FRAMEWORK",
    id: 44,
  },
  {
    name: "Ktor",
    type: "FRAMEWORK",
    id: 45,
  },
  {
    name: "Phoenix",
    type: "FRAMEWORK",
    id: 46,
  },
  {
    name: "Wt",
    type: "FRAMEWORK",
    id: 47,
  },
  {
    name: "Akka HTTP",
    type: "FRAMEWORK",
    id: 48,
  },
  {
    name: "Grails",
    type: "FRAMEWORK",
    id: 49,
  },
  {
    name: "ColdFusion",
    type: "FRAMEWORK",
    id: 50,
  },
  {
    name: "JHipster",
    type: "FRAMEWORK",
    id: 51,
  },
  {
    name: "Hapi",
    type: "FRAMEWORK",
    id: 52,
  },
  {
    name: "Koa",
    type: "FRAMEWORK",
    id: 53,
  },
  {
    name: "Mithril",
    type: "FRAMEWORK",
    id: 54,
  },
  {
    name: "Alpine",
    type: "FRAMEWORK",
    id: 55,
  },
  {
    name: "Backbone",
    type: "FRAMEWORK",
    id: 56,
  },
  {
    name: "Knockout",
    type: "FRAMEWORK",
    id: 57,
  },
  {
    name: "Marionette",
    type: "FRAMEWORK",
    id: 58,
  },
  {
    name: "Riot",
    type: "FRAMEWORK",
    id: 59,
  },
  {
    name: "Stimulus",
    type: "FRAMEWORK",
    id: 60,
  },
  {
    name: "Webix",
    type: "FRAMEWORK",
    id: 61,
  },
  {
    name: "Ext ",
    type: "FRAMEWORK",
    id: 62,
  },
  {
    name: "Dojo",
    type: "FRAMEWORK",
    id: 63,
  },
  {
    name: "Qooxdoo",
    type: "FRAMEWORK",
    id: 64,
  },
  {
    name: "SAPUI5",
    type: "FRAMEWORK",
    id: 65,
  },
  {
    name: "OpenUI5",
    type: "FRAMEWORK",
    id: 66,
  },
  {
    name: "PrimeFaces",
    type: "FRAMEWORK",
    id: 67,
  },
  {
    name: "RichFaces",
    type: "FRAMEWORK",
    id: 68,
  },
  {
    name: "IceFaces",
    type: "FRAMEWORK",
    id: 69,
  },
  {
    name: "Tapestry",
    type: "FRAMEWORK",
    id: 70,
  },
  {
    name: "ZK",
    type: "FRAMEWORK",
    id: 71,
  },
  {
    name: "GWT",
    type: "FRAMEWORK",
    id: 72,
  },
  {
    name: "Vaadin Flow",
    type: "FRAMEWORK",
    id: 73,
  },
  {
    name: "Liferay",
    type: "FRAMEWORK",
    id: 74,
  },
  {
    name: "Stripes",
    type: "FRAMEWORK",
    id: 75,
  },
  {
    name: "AppFuse",
    type: "FRAMEWORK",
    id: 76,
  },
  {
    name: "TurboGears",
    type: "FRAMEWORK",
    id: 77,
  },
  {
    name: "Cherrypy",
    type: "FRAMEWORK",
    id: 78,
  },
  {
    name: "Web2py",
    type: "FRAMEWORK",
    id: 79,
  },
  {
    name: "Bower",
    type: "FRAMEWORK",
    id: 80,
  },
  {
    name: "Webpack",
    type: "FRAMEWORK",
    id: 81,
  },
  {
    name: "Grunt",
    type: "FRAMEWORK",
    id: 82,
  },
  {
    name: "Gulp",
    type: "FRAMEWORK",
    id: 83,
  },
  {
    name: "Rollup",
    type: "FRAMEWORK",
    id: 84,
  },
  {
    name: "Parcel",
    type: "FRAMEWORK",
    id: 85,
  },
  {
    name: "Browserify",
    type: "FRAMEWORK",
    id: 86,
  },
  {
    name: "Vite",
    type: "FRAMEWORK",
    id: 87,
  },
  {
    name: "Snowpack",
    type: "FRAMEWORK",
    id: 88,
  },
  {
    name: "Alfresco",
    type: "FRAMEWORK",
    id: 90,
  },
  {
    name: "Caboose",
    type: "FRAMEWORK",
    id: 91,
  },
  {
    name: "ActiveScaffold",
    type: "FRAMEWORK",
    id: 92,
  },
  {
    name: "Unpoly",
    type: "FRAMEWORK",
    id: 93,
  },
  {
    name: "Turbolinks",
    type: "FRAMEWORK",
    id: 94,
  },
  {
    name: "StimulusReflex",
    type: "FRAMEWORK",
    id: 95,
  },
  {
    name: "Hotwire",
    type: "FRAMEWORK",
    id: 96,
  },
  {
    name: "Livewire",
    type: "FRAMEWORK",
    id: 97,
  },
  {
    name: "Phoenix LiveView",
    type: "FRAMEWORK",
    id: 98,
  },
  {
    name: "Surface",
    type: "FRAMEWORK",
    id: 99,
  },
  {
    name: "Inertia",
    type: "FRAMEWORK",
    id: 100,
  },
  {
    name: "Capacitor",
    type: "FRAMEWORK",
    id: 101,
  },
  {
    name: "Quasar",
    type: "FRAMEWORK",
    id: 102,
  },
  {
    name: "NativeScript",
    type: "FRAMEWORK",
    id: 103,
  },
  {
    name: "Onsen UI",
    type: "FRAMEWORK",
    id: 104,
  },
  {
    name: "Ionic",
    type: "FRAMEWORK",
    id: 105,
  },

  {
    name: "Tabris",
    type: "FRAMEWORK",
    id: 107,
  },
  {
    name: "Monaca",
    type: "FRAMEWORK",
    id: 108,
  },
  {
    name: "Weex",
    type: "FRAMEWORK",
    id: 109,
  },
  {
    name: "PWA Studio",
    type: "FRAMEWORK",
    id: 110,
  },
  {
    name: "Stencil",
    type: "FRAMEWORK",
    id: 111,
  },
  {
    name: "React Native",
    type: "FRAMEWORK",
    id: 112,
  },
  {
    name: "Flutter Web",
    type: "FRAMEWORK",
    id: 113,
  },
  {
    name: "Expo",
    type: "FRAMEWORK",
    id: 114,
  },
  {
    name: "NativeBase",
    type: "FRAMEWORK",
    id: 115,
  },
  {
    name: "Gatsby",
    type: "FRAMEWORK",
    id: 116,
  },
  {
    name: "Jekyll",
    type: "FRAMEWORK",
    id: 117,
  },
  {
    name: "Hugo",
    type: "FRAMEWORK",
    id: 118,
  },
  {
    name: "Eleventy",
    type: "FRAMEWORK",
    id: 119,
  },
  {
    name: "Hexo",
    type: "FRAMEWORK",
    id: 120,
  },
  {
    name: "Pelican",
    type: "FRAMEWORK",
    id: 121,
  },
  {
    name: "Zola",
    type: "FRAMEWORK",
    id: 122,
  },
  {
    name: "MkDocs",
    type: "FRAMEWORK",
    id: 123,
  },
  {
    name: "Antora",
    type: "FRAMEWORK",
    id: 124,
  },
  {
    name: "Docusaurus",
    type: "FRAMEWORK",
    id: 125,
  },
  {
    name: "Sapper",
    type: "FRAMEWORK",
    id: 126,
  },
  {
    name: "Blitz",
    type: "FRAMEWORK",
    id: 127,
  },
  {
    name: "Remix",
    type: "FRAMEWORK",
    id: 128,
  },
  {
    name: "Redwood",
    type: "FRAMEWORK",
    id: 129,
  },
  {
    name: "Dojo Toolkit",
    type: "FRAMEWORK",
    id: 130,
  },
  {
    name: "Enyo",
    type: "FRAMEWORK",
    id: 131,
  },
  {
    name: "MooTools",
    type: "FRAMEWORK",
    id: 132,
  },
  {
    name: "Prototype",
    type: "FRAMEWORK",
    id: 133,
  },
  {
    name: "Spry",
    type: "FRAMEWORK",
    id: 134,
  },
  {
    name: "SproutCore",
    type: "FRAMEWORK",
    id: 135,
  },
  {
    name: "Sammy",
    type: "FRAMEWORK",
    id: 136,
  },
  {
    name: "T3",
    type: "FRAMEWORK",
    id: 137,
  },
  {
    name: "Thorax",
    type: "FRAMEWORK",
    id: 138,
  },
  {
    name: "Flight",
    type: "FRAMEWORK",
    id: 139,
  },
  {
    name: "Hull",
    type: "FRAMEWORK",
    id: 140,
  },
  {
    name: "Flatiron",
    type: "FRAMEWORK",
    id: 141,
  },
  {
    name: "Lavaca",
    type: "FRAMEWORK",
    id: 142,
  },
  {
    name: "Manos",
    type: "FRAMEWORK",
    id: 143,
  },
  {
    name: "Spine",
    type: "FRAMEWORK",
    id: 144,
  },
  {
    name: "Omniscient",
    type: "FRAMEWORK",
    id: 145,
  },
  {
    name: "Page",
    type: "FRAMEWORK",
    id: 146,
  },
  {
    name: "Ampersand",
    type: "FRAMEWORK",
    id: 147,
  },
  {
    name: "Rendr",
    type: "FRAMEWORK",
    id: 148,
  },
  {
    name: "Derby",
    type: "FRAMEWORK",
    id: 149,
  },
  {
    name: "Lumbar",
    type: "FRAMEWORK",
    id: 150,
  },
  {
    name: "Brunch",
    type: "FRAMEWORK",
    id: 151,
  },
  {
    name: "Chaplin",
    type: "FRAMEWORK",
    id: 152,
  },
  {
    name: "CanJS",
    type: "FRAMEWORK",
    id: 153,
  },
  {
    name: "ExtAngular",
    type: "FRAMEWORK",
    id: 154,
  },
  {
    name: "JSF",
    type: "FRAMEWORK",
    id: 155,
  },
  {
    name: "Seaside",
    type: "FRAMEWORK",
    id: 156,
  },
  {
    name: "Nitrogen",
    type: "FRAMEWORK",
    id: 157,
  },
  {
    name: "Aida/Web",
    type: "FRAMEWORK",
    id: 158,
  },
  {
    name: "Yesod",
    type: "FRAMEWORK",
    id: 159,
  },
  {
    name: "Snap",
    type: "FRAMEWORK",
    id: 160,
  },
  {
    name: "IHP",
    type: "FRAMEWORK",
    id: 161,
  },
  {
    name: "Happstack",
    type: "FRAMEWORK",
    id: 162,
  },
  {
    name: "Perl Dancer",
    type: "FRAMEWORK",
    id: 163,
  },
  {
    name: "Mojolicious",
    type: "FRAMEWORK",
    id: 164,
  },
  {
    name: "Catalyst",
    type: "FRAMEWORK",
    id: 165,
  },
  {
    name: "PHPixie",
    type: "FRAMEWORK",
    id: 166,
  },
  {
    name: "Lumen",
    type: "FRAMEWORK",
    id: 167,
  },
  {
    name: "FuelPHP",
    type: "FRAMEWORK",
    id: 168,
  },
  {
    name: "Phalcon",
    type: "FRAMEWORK",
    id: 169,
  },
  {
    name: "Kohana",
    type: "FRAMEWORK",
    id: 170,
  },
  {
    name: "Zend ",
    type: "FRAMEWORK",
    id: 171,
  },
  {
    name: "Zend Expressive",
    type: "FRAMEWORK",
    id: 172,
  },
  {
    name: "Aura",
    type: "FRAMEWORK",
    id: 173,
  },
  {
    name: "Slim ",
    type: "FRAMEWORK",
    id: 174,
  },
  {
    name: "PSR-7",
    type: "FRAMEWORK",
    id: 175,
  },
  {
    name: "Swoole",
    type: "FRAMEWORK",
    id: 176,
  },
  {
    name: "Ratchet",
    type: "FRAMEWORK",
    id: 177,
  },
  {
    name: "Guzzle",
    type: "FRAMEWORK",
    id: 178,
  },
  {
    name: "OmniFaces",
    type: "FRAMEWORK",
    id: 179,
  },
  {
    name: "PrimeNG",
    type: "FRAMEWORK",
    id: 180,
  },
  {
    name: "Angular Material",
    type: "FRAMEWORK",
    id: 181,
  },
  {
    name: "Material-UI",
    type: "FRAMEWORK",
    id: 182,
  },
  {
    name: "Chakra UI",
    type: "FRAMEWORK",
    id: 183,
  },
  {
    name: "Blueprint",
    type: "FRAMEWORK",
    id: 184,
  },
  {
    name: "Ant Design",
    type: "FRAMEWORK",
    id: 185,
  },
  {
    name: "Carbon Design",
    type: "FRAMEWORK",
    id: 186,
  },
  {
    name: "PatternFly",
    type: "FRAMEWORK",
    id: 187,
  },
  {
    name: "Semantic UI",
    type: "FRAMEWORK",
    id: 188,
  },
  {
    name: "Shoelace",
    type: "FRAMEWORK",
    id: 189,
  },
  {
    name: "Formik",
    type: "FRAMEWORK",
    id: 190,
  },
  {
    name: "Redux Toolkit",
    type: "FRAMEWORK",
    id: 191,
  },
  {
    name: "RxJS",
    type: "FRAMEWORK",
    id: 192,
  },
  {
    name: "MobX",
    type: "FRAMEWORK",
    id: 193,
  },
];
